//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Systems/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""World"",
            ""id"": ""9322a261-ae71-436d-afc4-fb2a4d499535"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""dfa1c10c-8617-439e-8893-690083d2d881"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrowItem"",
                    ""type"": ""Button"",
                    ""id"": ""f27f1dca-3eaa-46c2-8d29-c7f1dcd17ab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PickItem"",
                    ""type"": ""Button"",
                    ""id"": ""59c55008-7b56-42d8-a223-587766d98868"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""4c5a6e83-b5c3-4a3a-8bc5-1dbda3d20b2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateRight"",
                    ""type"": ""Button"",
                    ""id"": ""b3c56447-c4b0-4b18-8a08-80a226ddc010"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""073f3618-2396-44db-a22c-903ed3c8d100"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d54cdbb6-8428-4a49-9602-f50051b48a95"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6036355-1b59-409a-9b00-a7ae922c2ea9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PickItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8e3df8bb-4f43-47ed-ab45-a3ff604c6737"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a9993f51-1178-4516-b11a-db98ca238193"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""05a704ad-6a19-4c3c-a8e7-740ae25edf89"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""90560517-ba7a-4370-b157-45d0fcad0f2a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cdb4bf9e-ff39-43a6-9ba6-7cea4a3ce5c3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f5afcce0-966d-48b9-932c-3f9e56156e5b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34e65525-eb22-4f8a-8bc5-749bb8af7b62"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""154880bf-5f0c-4d97-9c09-e36ce8aeb511"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // World
        m_World = asset.FindActionMap("World", throwIfNotFound: true);
        m_World_Movement = m_World.FindAction("Movement", throwIfNotFound: true);
        m_World_ThrowItem = m_World.FindAction("ThrowItem", throwIfNotFound: true);
        m_World_PickItem = m_World.FindAction("PickItem", throwIfNotFound: true);
        m_World_Inventory = m_World.FindAction("Inventory", throwIfNotFound: true);
        m_World_InventoryNavigateRight = m_World.FindAction("InventoryNavigateRight", throwIfNotFound: true);
        m_World_InventoryNavigateLeft = m_World.FindAction("InventoryNavigateLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // World
    private readonly InputActionMap m_World;
    private IWorldActions m_WorldActionsCallbackInterface;
    private readonly InputAction m_World_Movement;
    private readonly InputAction m_World_ThrowItem;
    private readonly InputAction m_World_PickItem;
    private readonly InputAction m_World_Inventory;
    private readonly InputAction m_World_InventoryNavigateRight;
    private readonly InputAction m_World_InventoryNavigateLeft;
    public struct WorldActions
    {
        private @PlayerInputActions m_Wrapper;
        public WorldActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_World_Movement;
        public InputAction @ThrowItem => m_Wrapper.m_World_ThrowItem;
        public InputAction @PickItem => m_Wrapper.m_World_PickItem;
        public InputAction @Inventory => m_Wrapper.m_World_Inventory;
        public InputAction @InventoryNavigateRight => m_Wrapper.m_World_InventoryNavigateRight;
        public InputAction @InventoryNavigateLeft => m_Wrapper.m_World_InventoryNavigateLeft;
        public InputActionMap Get() { return m_Wrapper.m_World; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorldActions set) { return set.Get(); }
        public void SetCallbacks(IWorldActions instance)
        {
            if (m_Wrapper.m_WorldActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @ThrowItem.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @ThrowItem.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @ThrowItem.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @PickItem.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnPickItem;
                @PickItem.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnPickItem;
                @PickItem.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnPickItem;
                @Inventory.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @InventoryNavigateRight.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateRight.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateRight.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateLeft.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
            }
            m_Wrapper.m_WorldActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @ThrowItem.started += instance.OnThrowItem;
                @ThrowItem.performed += instance.OnThrowItem;
                @ThrowItem.canceled += instance.OnThrowItem;
                @PickItem.started += instance.OnPickItem;
                @PickItem.performed += instance.OnPickItem;
                @PickItem.canceled += instance.OnPickItem;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @InventoryNavigateRight.started += instance.OnInventoryNavigateRight;
                @InventoryNavigateRight.performed += instance.OnInventoryNavigateRight;
                @InventoryNavigateRight.canceled += instance.OnInventoryNavigateRight;
                @InventoryNavigateLeft.started += instance.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.performed += instance.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.canceled += instance.OnInventoryNavigateLeft;
            }
        }
    }
    public WorldActions @World => new WorldActions(this);
    public interface IWorldActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnThrowItem(InputAction.CallbackContext context);
        void OnPickItem(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnInventoryNavigateRight(InputAction.CallbackContext context);
        void OnInventoryNavigateLeft(InputAction.CallbackContext context);
    }
}
