//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Systems/Inputs/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""World"",
            ""id"": ""9322a261-ae71-436d-afc4-fb2a4d499535"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""dfa1c10c-8617-439e-8893-690083d2d881"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ThrowItem"",
                    ""type"": ""Button"",
                    ""id"": ""f27f1dca-3eaa-46c2-8d29-c7f1dcd17ab4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action"",
                    ""type"": ""Button"",
                    ""id"": ""59c55008-7b56-42d8-a223-587766d98868"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""4c5a6e83-b5c3-4a3a-8bc5-1dbda3d20b2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateRight"",
                    ""type"": ""Button"",
                    ""id"": ""b3c56447-c4b0-4b18-8a08-80a226ddc010"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""073f3618-2396-44db-a22c-903ed3c8d100"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateUp"",
                    ""type"": ""Button"",
                    ""id"": ""2ba962d8-889c-43f6-9439-b747bb23b54d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryNavigateDown"",
                    ""type"": ""Button"",
                    ""id"": ""574a79d0-d870-476d-82da-4bd5bd79ce11"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryRight"",
                    ""type"": ""Button"",
                    ""id"": ""e7ecdf2b-e175-4e5d-9032-0ceffbe74753"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryLeft"",
                    ""type"": ""Button"",
                    ""id"": ""5743d8f8-392d-4f4e-88e2-7c469872e29a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d54cdbb6-8428-4a49-9602-f50051b48a95"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6036355-1b59-409a-9b00-a7ae922c2ea9"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8e3df8bb-4f43-47ed-ab45-a3ff604c6737"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a9993f51-1178-4516-b11a-db98ca238193"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""05a704ad-6a19-4c3c-a8e7-740ae25edf89"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""90560517-ba7a-4370-b157-45d0fcad0f2a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cdb4bf9e-ff39-43a6-9ba6-7cea4a3ce5c3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f5afcce0-966d-48b9-932c-3f9e56156e5b"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34e65525-eb22-4f8a-8bc5-749bb8af7b62"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""494da026-71e3-4c0e-9cdc-4dcacfea9a8f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""154880bf-5f0c-4d97-9c09-e36ce8aeb511"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""081b68a3-279a-4678-824a-7e9c3cbd5f25"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84ade16c-dd9f-4b84-9bc7-b33ec6fcd19b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""366020c4-905b-4ac7-8ba3-16602bc5db5a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31ef7d00-ec79-40f8-8bdc-1cdb2112076d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""efe8ff33-c7e9-439b-9d70-e20a69fc32b4"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryNavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56829e36-4735-4bfd-ad3d-bf5bfe06f787"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d70ed93-d94a-49c5-8c52-80f467a29c49"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // World
        m_World = asset.FindActionMap("World", throwIfNotFound: true);
        m_World_Movement = m_World.FindAction("Movement", throwIfNotFound: true);
        m_World_ThrowItem = m_World.FindAction("ThrowItem", throwIfNotFound: true);
        m_World_Action = m_World.FindAction("Action", throwIfNotFound: true);
        m_World_Inventory = m_World.FindAction("Inventory", throwIfNotFound: true);
        m_World_InventoryNavigateRight = m_World.FindAction("InventoryNavigateRight", throwIfNotFound: true);
        m_World_InventoryNavigateLeft = m_World.FindAction("InventoryNavigateLeft", throwIfNotFound: true);
        m_World_InventoryNavigateUp = m_World.FindAction("InventoryNavigateUp", throwIfNotFound: true);
        m_World_InventoryNavigateDown = m_World.FindAction("InventoryNavigateDown", throwIfNotFound: true);
        m_World_InventoryRight = m_World.FindAction("InventoryRight", throwIfNotFound: true);
        m_World_InventoryLeft = m_World.FindAction("InventoryLeft", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // World
    private readonly InputActionMap m_World;
    private IWorldActions m_WorldActionsCallbackInterface;
    private readonly InputAction m_World_Movement;
    private readonly InputAction m_World_ThrowItem;
    private readonly InputAction m_World_Action;
    private readonly InputAction m_World_Inventory;
    private readonly InputAction m_World_InventoryNavigateRight;
    private readonly InputAction m_World_InventoryNavigateLeft;
    private readonly InputAction m_World_InventoryNavigateUp;
    private readonly InputAction m_World_InventoryNavigateDown;
    private readonly InputAction m_World_InventoryRight;
    private readonly InputAction m_World_InventoryLeft;
    public struct WorldActions
    {
        private @PlayerInputActions m_Wrapper;
        public WorldActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_World_Movement;
        public InputAction @ThrowItem => m_Wrapper.m_World_ThrowItem;
        public InputAction @Action => m_Wrapper.m_World_Action;
        public InputAction @Inventory => m_Wrapper.m_World_Inventory;
        public InputAction @InventoryNavigateRight => m_Wrapper.m_World_InventoryNavigateRight;
        public InputAction @InventoryNavigateLeft => m_Wrapper.m_World_InventoryNavigateLeft;
        public InputAction @InventoryNavigateUp => m_Wrapper.m_World_InventoryNavigateUp;
        public InputAction @InventoryNavigateDown => m_Wrapper.m_World_InventoryNavigateDown;
        public InputAction @InventoryRight => m_Wrapper.m_World_InventoryRight;
        public InputAction @InventoryLeft => m_Wrapper.m_World_InventoryLeft;
        public InputActionMap Get() { return m_Wrapper.m_World; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(WorldActions set) { return set.Get(); }
        public void SetCallbacks(IWorldActions instance)
        {
            if (m_Wrapper.m_WorldActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnMovement;
                @ThrowItem.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @ThrowItem.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @ThrowItem.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnThrowItem;
                @Action.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnAction;
                @Action.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnAction;
                @Action.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnAction;
                @Inventory.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventory;
                @InventoryNavigateRight.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateRight.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateRight.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateRight;
                @InventoryNavigateLeft.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateLeft;
                @InventoryNavigateUp.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateUp;
                @InventoryNavigateUp.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateUp;
                @InventoryNavigateUp.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateUp;
                @InventoryNavigateDown.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateDown;
                @InventoryNavigateDown.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateDown;
                @InventoryNavigateDown.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryNavigateDown;
                @InventoryRight.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryRight;
                @InventoryRight.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryRight;
                @InventoryRight.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryRight;
                @InventoryLeft.started -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryLeft;
                @InventoryLeft.performed -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryLeft;
                @InventoryLeft.canceled -= m_Wrapper.m_WorldActionsCallbackInterface.OnInventoryLeft;
            }
            m_Wrapper.m_WorldActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @ThrowItem.started += instance.OnThrowItem;
                @ThrowItem.performed += instance.OnThrowItem;
                @ThrowItem.canceled += instance.OnThrowItem;
                @Action.started += instance.OnAction;
                @Action.performed += instance.OnAction;
                @Action.canceled += instance.OnAction;
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @InventoryNavigateRight.started += instance.OnInventoryNavigateRight;
                @InventoryNavigateRight.performed += instance.OnInventoryNavigateRight;
                @InventoryNavigateRight.canceled += instance.OnInventoryNavigateRight;
                @InventoryNavigateLeft.started += instance.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.performed += instance.OnInventoryNavigateLeft;
                @InventoryNavigateLeft.canceled += instance.OnInventoryNavigateLeft;
                @InventoryNavigateUp.started += instance.OnInventoryNavigateUp;
                @InventoryNavigateUp.performed += instance.OnInventoryNavigateUp;
                @InventoryNavigateUp.canceled += instance.OnInventoryNavigateUp;
                @InventoryNavigateDown.started += instance.OnInventoryNavigateDown;
                @InventoryNavigateDown.performed += instance.OnInventoryNavigateDown;
                @InventoryNavigateDown.canceled += instance.OnInventoryNavigateDown;
                @InventoryRight.started += instance.OnInventoryRight;
                @InventoryRight.performed += instance.OnInventoryRight;
                @InventoryRight.canceled += instance.OnInventoryRight;
                @InventoryLeft.started += instance.OnInventoryLeft;
                @InventoryLeft.performed += instance.OnInventoryLeft;
                @InventoryLeft.canceled += instance.OnInventoryLeft;
            }
        }
    }
    public WorldActions @World => new WorldActions(this);
    public interface IWorldActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnThrowItem(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnInventory(InputAction.CallbackContext context);
        void OnInventoryNavigateRight(InputAction.CallbackContext context);
        void OnInventoryNavigateLeft(InputAction.CallbackContext context);
        void OnInventoryNavigateUp(InputAction.CallbackContext context);
        void OnInventoryNavigateDown(InputAction.CallbackContext context);
        void OnInventoryRight(InputAction.CallbackContext context);
        void OnInventoryLeft(InputAction.CallbackContext context);
    }
}
